version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
    assignees: ["KeidsID"]
    labels: ["dependabot", "github"]

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
    assignees: ["KeidsID"]
    labels: ["dependabot"]
