version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["dependabot", "github"]

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["dependabot"]
